---
    name: release builder

    on:
      push:
        tags:
          - "v*"

    jobs:
      release:
        name: build and release
        runs-on: ubuntu-20.04
        steps:
          - name: install pixz
            run: sudo apt-get install -y pixz

          - name: checkout the repos
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              fetch-tags: true
              submodules: recursive

          - name: install golang
            uses: actions/setup-go@v5
            with:
              go-version: "1.22"
              check-latest: true

          - name: install rust
            uses: actions-rs/toolchain@v1
            with:
              toolchain: stable
              target: x86_64-unknown-linux-gnu
              override: true
              profile: minimal

          - name: Set version
            run: |
              echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

          - name: build binaries and archives
            run: |
              make build balls

          - name: make release and upload archives
            uses: ncipollo/release-action@v1
            with:
              name: "Berastribute ${{ env.VERSION }}"
              draft: true
              artifacts: ".balls/*"
              body: |
                Berastribute Release ${{ env.VERSION }}

                ## Binaries
                - Linux (amd64)
